/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.armantec.bms.author.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Author service. Represents a row in the &quot;Bms_Author&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.armantec.bms.author.model.impl.AuthorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.armantec.bms.author.model.impl.AuthorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Author
 * @generated
 */
@ProviderType
public interface AuthorModel
	extends BaseModel<Author>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author model instance should use the {@link Author} interface instead.
	 */

	/**
	 * Returns the primary key of this author.
	 *
	 * @return the primary key of this author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author.
	 *
	 * @param primaryKey the primary key of this author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this author.
	 *
	 * @return the uuid of this author
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this author.
	 *
	 * @param uuid the uuid of this author
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the author ID of this author.
	 *
	 * @return the author ID of this author
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author.
	 *
	 * @param authorId the author ID of this author
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the group ID of this author.
	 *
	 * @return the group ID of this author
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this author.
	 *
	 * @param groupId the group ID of this author
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this author.
	 *
	 * @return the company ID of this author
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this author.
	 *
	 * @param companyId the company ID of this author
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this author.
	 *
	 * @return the user ID of this author
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this author.
	 *
	 * @param userId the user ID of this author
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this author.
	 *
	 * @return the user uuid of this author
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this author.
	 *
	 * @param userUuid the user uuid of this author
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this author.
	 *
	 * @return the user name of this author
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this author.
	 *
	 * @param userName the user name of this author
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this author.
	 *
	 * @return the create date of this author
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this author.
	 *
	 * @param createDate the create date of this author
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this author.
	 *
	 * @return the modified date of this author
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this author.
	 *
	 * @param modifiedDate the modified date of this author
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ID of this author.
	 *
	 * @return the ID of this author
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this author.
	 *
	 * @param id the ID of this author
	 */
	public void setId(String id);

	/**
	 * Returns the name of this author.
	 *
	 * @return the name of this author
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this author.
	 *
	 * @param name the name of this author
	 */
	public void setName(String name);

	/**
	 * Returns the author book of this author.
	 *
	 * @return the author book of this author
	 */
	@AutoEscape
	public String getAuthorBook();

	/**
	 * Sets the author book of this author.
	 *
	 * @param authorBook the author book of this author
	 */
	public void setAuthorBook(String authorBook);

	@Override
	public Author cloneWithOriginalValues();

}